### ISSUE TITLE
About the use of loophp/collection

### ISSUE THREAD

**Issue by drupol** [scrawler-labs/arca-orm#1]
Hey there,

I'm glad and honoured that you're using [loophp/collection](https://github.com/loophp/collection), but I think you should not do this.
By "this", I mean [copying the content of the Collection class into your namespace](https://github.com/scrawler-labs/arca-orm/blob/main/src/Collection.php).

When doing that, you basically discard all the upstream fixes and features that might comes in loophp/collection in the future.

The best option is to directly rely on the Collection class and its interface by using Composition pattern.

I quickly drafted something for you here so you can get some inspirations: https://gist.github.com/drupol/c8f97902184decc7fbf004120fe89fc0

Note that you are not "forced" to implements ALL the methods of the Collection interface, you could have your own interface and just implements the minimum you need and just using loophp/collection internally without never exposing everything.

Let me know if you need further help.

Thx

**Comment by ipranjal** [comment]
@drupol thanks for the suggestion , seems like a really good idea , this would even help me to get read of my coverage issues as I did not wanted to add the duplicated loophp implementation inside coverage report .

also @drupol even I had fear of the same issue of maintaining upstream changes from loophp . I’ll start working on PR today and hope to resolve it ASAP

**Comment by ipranjal** [comment]
thank you @drupol

**Comment by drupol** [comment]
Super, you got it right :)

Glad to have helped !

Keep up the good work.
