### ISSUE TITLE
via Reddit : ability to switch between using uuid and id 

### ISSUE THREAD

**Issue by ipranjal** [scrawler-labs/arca-orm#2]
Author u/pfsalter

**Comment by nathansalter** [comment]
Just some context from the [reddit thread](https://www.reddit.com/r/PHP/comments/v0hk9f/comment/iaj3x3s/?utm_source=share&utm_medium=web2x&context=3): UUIDs can be a better method of IDs in many cases as you don't have to wait for the database to respond before linking with other entities. You can also dispatch messages etc. assuming that the UUIDs will eventually be in the database. This is also better for sharding across multiple servers and using in other types of databases (e.g. NoSQL, Document stores, Cache DBs)

**Comment by ipranjal** [comment]
using `$db->useUUID()` will now switch to using UUID rather than auto increment key

**Comment by ipranjal** [comment]
doc updated here https://github.com/scrawler-labs/arca-orm/wiki
